# Generated by Django 4.1.7 on 2023-03-25 09:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="blogpost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("content", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("slug", models.CharField(max_length=1000)),
                (
                    "image",
                    models.ImageField(blank="True", null="True", upload_to="images/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("upload_to", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subscribers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
